insert into Rodada values
(null, 'ida', 'Rodada 1'),
(null, 'volta', 'Rodada 1'),
(null, 'ida', 'Rodada 2'),
(null, 'volta', 'Rodada 2'),
(null, 'ida', 'Rodada 3'),
(null, 'volta', 'Rodada 3'),
(null, 'Rodada 1', 'Grupos'),
(null, 'Rodada 2', 'Grupos'),
(null, 'Rodada 3', 'Grupos'),
(null, 'Rodada 4', 'Grupos'),
(null, 'Rodada 5', 'Grupos'),
(null, 'Rodada 6', 'Grupos'),
(null, 'ida', 'Oitavas'),
(null, 'volta', 'Oitavas'),
(null, 'ida', 'Quartas'),
(null, 'volta', 'Quartas'),
(null, 'ida', 'Semi'),
(null, 'volta', 'Semi'),
(null, 'Unico', 'Final');

insert into Pais values
(null,'Argentina'),
(null,'Bolívia'),
(null,'Brasil'),
(null,'Chile'),
(null,'Colômbia'),
(null,'Equador'),
(null,'Paraguai'),
(null,'Peru'),
(null,'Uruguaí'),
(null,'Venezuela');

insert into Times values
(null,'Argentinos Juniors','AGJ','AGJ.png',6,1,'30,61 Mi. €',1),
(null,'Boca Juniors','BOC','BOC.png',3,2,'94,80 Mi. €',1),
(null,'Defensa y Justicia','DYJ','DYJ.png',6,4,'35,28 Mi. €',1),
(null,'Racing','RAC','RAC.png',5,2,'44,10 Mi. €',1),
(null,'River Plate','RIV','RIV.png',4,3,'114,45 Mi. €',1),
(null,'San Lorenzo','SLO','SLO.png',6,6,'45,15 Mi. €',1),
(null,'Velez','VEL','VEL.png',8,7,'66,03 Mi. €',1),
(null,'Always Ready','ALW','ALW.png',6,4,'9,58 Mi. €',2),
(null,'Bolívar','BOL','BOL.png',7,5,'9,84 Mi. €',2),
(null,'Royal Pari','ROY','ROY.png',2,5,'7,30 Mi. €',2),
(null,'The Strongest','STR','STR.png',2,10,'7,35 Mi. €',2),
(null,'Atlético Mineiro','CAM','CAM.png',10,3,'82,40 Mi. €',3),
(null,'Flamengo','FLA','FLA.png',12,7,'128,05 Mi. €',3),
(null,'Fluminense','FLU','FLU.png',6,4,'50,68 Mi. €',3),
(null,'Gremio','GRE','GRE.png',10,6,'73,90 Mi. €',3),
(null,'Internacional','INT','INT.png',11,5,'71,65 Mi. €',3),
(null,'Palmeiras','PAL','PAL.png',11,3,'119,15 Mi. €',3),
(null,'Santos','SAN','SAN.png',14,9,'47,28 Mi. €',3),
(null,'São Paulo','SÃO','SÃO.png',6,1,'62,35 Mi. €',3),
(null,'Unión Española','UES','UES.png',3,6,'10,93 Mi. €',4),
(null,'Unión La Calera','ULC','ULC.png',5,10,'11,48 Mi. €',4),
(null,'Universidad Católica (CHI)','UCA','UCA.png',4,5,'19,63 Mi. €',4),
(null,'Universidad de Chile','UCH','UCH.png',1,3,'13,50  Mi. €',4),
(null,'America de Cali','AME','AME.png',2,7,'20,80 Mi. €',5),
(null,'Atlético Nacional','ANA','ANA.png',15,8,'20,88 Mi. €',5),
(null,'Junior Barranquilla','JUN','JUN.png',13,9,'23,63 Mi. €',5),
(null,'Santa Fe','SFE','SFE.png',3,5,'16,00 Mi. €',5),
(null,'Barcelona Guayaquil','BAR','BAR.png',7,2,'18,70 Mi. €',6),
(null,'Independiente Del Valle','IND','IND.png',15,12,'12,78  Mi. €',6),
(null,'LDU','LDU','LDU.png',8,9,'17,20 Mi. €',6),
(null,'Universidad Católica (EQU)','UNQ','UNQ.png',6,5,'10,70 Mi. €',6),
(null,'Cerro Porteño','CER','CER.png',3,4,'28,83 Mi. €',7),
(null,'Guaraní','GUA','GUA.png',5,7,'16,25 Mi. €',7),
(null,'Libertad','LIB','LIB.png',5,6,'29,95 Mi. €',7),
(null,'Olimpia','OLI','OLI.png',7,11,'26,00 Mi. €',7),
(null,'Ayacucho','IGD','IGD.png',2,8,'6,03 Mi. €',8),
(null,'Sporting Cristal','SCR','SCR.png',1,7,'8,20 Mi. €',8),
(null,'Universidad César Vallejo','UCV','UCV.png',0,2,'6,55 Mi. €',8),
(null,'Universitario','UNI','UNI.png',3,11,'8,48 Mi. €',8),
(null,'Liverpool','LIV','LIV.png',2,4,'11,05 Mi. €',9),
(null,'Montevideo Wanderers','MON','MON.png',1,5,'7,15 Mi. €',9),
(null,'Nacional','NAC','NAC.png',5,9,'14,83 Mi. €',9),
(null,'Rentistas','REN','REN.png',2,4,'7,40 Mi. €',9),
(null,'Caracas','CAR','CAR.png',4,5,'5,75 Mi. €',10),
(null,'Deportivo Lara','LAR','LAR.png',2,3,'4,03 Mi. €',10),
(null,'Deportivo La Guaira','LAG','LAG.png',1,2,'5,10 Mi. €',10),
(null,'Deportivo Táchira','DTA','DTA.png',5,9,'4,78 Mi. €',10);

insert into dadosJogos values
(null,'Alfredo Vieira','2021-02-23','21:30',1);

insert into Jogos values
(2,31,1,'F');